Update custom.css
tnware/grav-theme-material-lite pull request #7
Opened 2017-02-13 18:01 UTC by diomed

2017-02-25 22:28 UTC, tnware approved these changes

2017-02-25 22:30 UTC, tnware requested changes
i'm unable to see the scrollbar change to blue

2017-02-25 22:32 UTC, tnware approved these changes

2017-02-25 22:36 UTC, merged

2017-02-25 22:41 UTC, diomed commented
what browser do you use? 
I believe in Chrome it changes.

2017-02-26 16:36 UTC, diomed commented
Vivaldi and Chrome display it, I'm not sure about Opera [maybe]

Firefox doesn't support it, unfortunately, AFAIK.